# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossfity', '0002_auto_20170123_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachapplication',
            name='status',
            field=models.NullBooleanField(),
        ),
    ]
