# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossfity', '0003_auto_20170123_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachapplication',
            name='pass_mail',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='coachapplication',
            name='pass_phone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
