# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossfity', '0005_coach_sms_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachapplication',
            name='pass_coach_aded',
            field=models.BooleanField(default=False),
        ),
    ]
