# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossfity', '0006_coachapplication_pass_coach_aded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coachapplication',
            old_name='pass_coach_aded',
            new_name='pass_coach_added',
        ),
    ]
