# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossfity', '0007_auto_20170201_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_name', models.CharField(max_length=128)),
                ('tool', models.CharField(blank=True, max_length=128, null=True)),
                ('kg', models.SmallIntegerField(blank=True, null=True)),
                ('lbs', models.SmallIntegerField(blank=True, null=True)),
                ('poods', models.CharField(blank=True, max_length=32, null=True)),
                ('height_meters', models.CharField(blank=True, max_length=32, null=True)),
                ('height_ft', models.CharField(blank=True, max_length=32, null=True)),
                ('distance_meters', models.SmallIntegerField(blank=True, null=True)),
                ('distance_miles', models.SmallIntegerField(blank=True, null=True)),
                ('calories', models.SmallIntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('OLY', 'OLY - Olympic Weightlifting'), ('GYM', 'GYM Gymnastics'), ('METCON', 'METCON Met-Con')], max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='WOD_amrap',
        ),
        migrations.DeleteModel(
            name='WOD_emom',
        ),
        migrations.DeleteModel(
            name='WOD_interval',
        ),
        migrations.DeleteModel(
            name='WOD_tabata',
        ),
    ]
