# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossfity', '0008_auto_20170218_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
