# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('crossfity', '0009_auto_20170218_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('OLY', 'OLY - Olympic Weightlifting'), ('GYM', 'GYM Gymnastics'), ('METCON', 'METCON Met-Con')], max_length=15)),
                ('kind', models.CharField(choices=[('AMRAP', 'AMRAP As Many Rounds As Possible'), ('EMOM', 'EMOM Every Minute On Minute'), ('INTERVAL', 'Interval reounds: work:rest'), ('21-15-9', '21-15-9 formula')], max_length=15)),
                ('rounds', models.SmallIntegerField(blank=True, null=True)),
                ('time_cap', models.SmallIntegerField(blank=True, null=True)),
                ('reps_01', models.SmallIntegerField(blank=True, null=True)),
                ('reps_02', models.SmallIntegerField(blank=True, null=True)),
                ('reps_03', models.SmallIntegerField(blank=True, null=True)),
                ('reps_04', models.SmallIntegerField(blank=True, null=True)),
                ('reps_05', models.SmallIntegerField(blank=True, null=True)),
                ('reps_06', models.SmallIntegerField(blank=True, null=True)),
                ('reps_07', models.SmallIntegerField(blank=True, null=True)),
                ('reps_08', models.SmallIntegerField(blank=True, null=True)),
                ('reps_09', models.SmallIntegerField(blank=True, null=True)),
                ('reps_10', models.SmallIntegerField(blank=True, null=True)),
                ('reps_11', models.SmallIntegerField(blank=True, null=True)),
                ('reps_12', models.SmallIntegerField(blank=True, null=True)),
                ('reps_13', models.SmallIntegerField(blank=True, null=True)),
                ('reps_14', models.SmallIntegerField(blank=True, null=True)),
                ('reps_15', models.SmallIntegerField(blank=True, null=True)),
                ('emom_interval_work', models.SmallIntegerField(blank=True, null=True)),
                ('emom_interval_rest', models.SmallIntegerField(blank=True, null=True)),
                ('score', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='movement',
            unique_together=set([('move_name', 'tool', 'kg', 'lbs', 'poods', 'height_meters', 'height_ft', 'distance_meters', 'distance_miles', 'calories')]),
        ),
        migrations.AddField(
            model_name='element',
            name='mov_14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mov 14+', to='crossfity.Movement'),
        ),
        migrations.AddField(
            model_name='element',
            name='move_01',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mov 01+', to='crossfity.Movement'),
        ),
        migrations.AddField(
            model_name='element',
            name='move_02',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mov 02+', to='crossfity.Movement'),
        ),
        migrations.AddField(
            model_name='element',
            name='move_03',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mov 03+', to='crossfity.Movement'),
        ),
        migrations.AddField(
            model_name='element',
            name='move_04',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mov 04+', to='crossfity.Movement'),
        ),
        migrations.AddField(
            model_name='element',
            name='move_05',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mov 05+', to='crossfity.Movement'),
        ),
        migrations.AddField(
            model_name='element',
            name='move_06',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mov 06+', to='crossfity.Movement'),
        ),
        migrations.AddField(
            model_name='element',
            name='move_07',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mov 07+', to='crossfity.Movement'),
        ),
        migrations.AddField(
            model_name='element',
            name='move_08',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mov 08+', to='crossfity.Movement'),
        ),
        migrations.AddField(
            model_name='element',
            name='move_09',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mov 09+', to='crossfity.Movement'),
        ),
        migrations.AddField(
            model_name='element',
            name='move_10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mov 10+', to='crossfity.Movement'),
        ),
        migrations.AddField(
            model_name='element',
            name='move_11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mov 11+', to='crossfity.Movement'),
        ),
        migrations.AddField(
            model_name='element',
            name='move_12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mov 12+', to='crossfity.Movement'),
        ),
        migrations.AddField(
            model_name='element',
            name='move_13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mov 13+', to='crossfity.Movement'),
        ),
        migrations.AddField(
            model_name='element',
            name='move_15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mov 15+', to='crossfity.Movement'),
        ),
        migrations.AddField(
            model_name='element',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
