# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('crossfity', '0010_auto_20170218_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='WOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_publish', models.DateTimeField(blank=True, null=True)),
                ('score', models.CharField(blank=True, max_length=128, null=True)),
                ('athletes', models.ManyToManyField(to='crossfity.Athlete')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossfity.Coach')),
            ],
        ),
        migrations.AlterField(
            model_name='element',
            name='kind',
            field=models.CharField(choices=[('AMRAP', 'AMRAP As Many Rounds As Possible'), ('EMOM', 'EMOM Every Minute On Minute'), ('INTERVAL', 'Interval reounds: work:rest'), ('21-15-9', '21-15-9 formula'), ('DIST_ROW', 'Row for time')], max_length=15),
        ),
        migrations.AddField(
            model_name='wod',
            name='element_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crossfity.Element'),
        ),
        migrations.AddField(
            model_name='wod',
            name='element_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crossfity.Element'),
        ),
        migrations.AddField(
            model_name='wod',
            name='element_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crossfity.Element'),
        ),
        migrations.AddField(
            model_name='wod',
            name='element_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crossfity.Element'),
        ),
        migrations.AddField(
            model_name='wod',
            name='element_5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crossfity.Element'),
        ),
        migrations.AddField(
            model_name='wod',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
