# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crossfity', '0011_auto_20170218_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='kind',
            field=models.CharField(choices=[('AMRAP', 'AMRAP As Many Rounds As Possible'), ('EMOM', 'EMOM Every Minute On Minute'), ('INTERVAL', 'Interval reounds: work:rest'), ('21-15-9', '21-15-9 formula'), ('DIST_ROW', 'Row for time'), ('1RM OLY', '1RM max in OLY movement')], max_length=15),
        ),
        migrations.AlterField(
            model_name='wod',
            name='element_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crossfity.Element'),
        ),
        migrations.AlterField(
            model_name='wod',
            name='element_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crossfity.Element'),
        ),
        migrations.AlterField(
            model_name='wod',
            name='element_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crossfity.Element'),
        ),
        migrations.AlterField(
            model_name='wod',
            name='element_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crossfity.Element'),
        ),
    ]
