# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossfity', '0012_auto_20170218_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wod',
            name='athletes',
            field=models.ManyToManyField(blank=True, null=True, to='crossfity.Athlete'),
        ),
    ]
