# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('crossfity', '0013_auto_20170218_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='wodpersonal',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='wodpersonal',
            name='date_publish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wodpersonal',
            name='element_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crossfity.Element'),
        ),
        migrations.AddField(
            model_name='wodpersonal',
            name='element_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crossfity.Element'),
        ),
        migrations.AddField(
            model_name='wodpersonal',
            name='element_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crossfity.Element'),
        ),
        migrations.AddField(
            model_name='wodpersonal',
            name='element_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crossfity.Element'),
        ),
        migrations.AddField(
            model_name='wodpersonal',
            name='element_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crossfity.Element'),
        ),
        migrations.AddField(
            model_name='wodpersonal',
            name='score',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='wodpersonal',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='wodpersonal',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='wod',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='wod',
            name='element_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crossfity.Element'),
        ),
        migrations.AlterField(
            model_name='wod',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
