# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossfity', '0014_auto_20170218_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='TryDynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_elements', models.SmallIntegerField()),
            ],
        ),
    ]
