# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossfity', '0015_trydynamic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TryDynamic',
        ),
    ]
