# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crossfity', '0016_delete_trydynamic'),
    ]

    operations = [
        migrations.AddField(
            model_name='wodpersonal',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossfity.Athlete'),
            preserve_default=False,
        ),
    ]
