# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crossfity', '0017_wodpersonal_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wodpersonal',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crossfity.Athlete'),
        ),
    ]
