# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossfity', '0019_element_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='brief',
            field=models.CharField(max_length=128),
        ),
    ]
