# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossfity', '0020_auto_20170223_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='brief',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
