# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossfity', '0021_auto_20170223_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='mov_14',
            new_name='move_14',
        ),
    ]
